### PR TITLE
Upgrade elm-css

### PR DESCRIPTION
**Pull request by jmbockhorst**
Needed for use with some other packages. Doesn't seem to change anything here.

### CODE REVIEW

**Comment by abadi199** [comment]
Let's keep the lower bound for `elm-css` on `15.1.0`, that way we're not forcing people to upgrade their `elm-css` dependencies.

**Comment by jmbockhorst** [comment]
@abadi199 Sounds good, done.

**Comment by bdukes** [comment]
@abadi199 would you mind publishing a new version with this change?  @jmbockhorst is working on upgrading Engage Sports/AMS to 0.19, finally 😄 He apparently used some magic to publish https://package.elm-lang.org/packages/EngageSoftware/elm-engage-common/latest/ without this having been published first, but now we're stuck installing it until this package is published.

Let me know if it would be easier for @EngageSoftware to fork or take over maintenance or anything like that.  Thanks!

**Comment by abadi199** [comment]
@bdukes It's deployed as `2.0.2`. I'm more than happy to take any PR from y'all, but feel free to fork and publish it if I'm not able to respond fast enough.

**Comment by bdukes** [comment]
Thanks @abadi199!

**Pull request merged**
